spring.application.name=Notes

spring.datasource.url=jdbc:mysql://root:TTTeUXNZnbKuJLVTpzMjtXpoPZaKYAlr@caboose.proxy.rlwy.net:31958/railway
spring.datasource.username=root
spring.datasource.password=TTTeUXNZnbKuJLVTpzMjtXpoPZaKYAlr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true